### PR TITLE
Fix HTTP no content of 1xx and 204

### LINKED ISSUE #1610: 在brpc server中返回204时，body不为空
**Describe the bug (描述bug)**
在brpc server中返回204时，body不为空，不符合http规范，容易导致相关客户端断连接，引起平响开销和大量占用TIME_WAIT

**To Reproduce (复现方法)**
在example/echo_c++的server.cpp第60行，添加 cntl->http_response().set_status_code(brpc::HTTP_STATUS_NO_CONTENT);　以期望返回结果为204
image

结果确实是返回204了，但在抓包中发现，body是有内容的，不符合204的规范要求，导致相关服务会关闭长连接，抓包结果如下
image

**Expected behavior (期望行为)**
在返回204时，body应该为空，想请教一下，这个问题怎么修复呢？

**Versions (各种版本)**
OS:Ubuntu 18.04
Compiler: gcc 7.5
brpc: v0.9.7
protobuf: 3

**Additional context/screenshots (更多上下文/截图)**

### PR DESCRIPTION
**Pull request by chenBright**
### What problem does this PR solve?

Issue Number: Fix  #1610

Problem Summary:

### What is changed and the side effects?

Changed:

Side effects:
- Performance effects(性能影响):

- Breaking backward compatibility(向后兼容性): 

---
### Check List:
- Please make sure your changes are compilable(请确保你的更改可以通过编译).
- When providing us with a new feature, it is best to add related tests(如果你向我们增加一个新的功能, 请添加相关测试).
- Please follow [Contributor Covenant Code of Conduct](../../master/CODE_OF_CONDUCT.md).(请遵循贡献者准则).

### CODE REVIEW

**Comment by wwbmmm** [comment]
LGTM

File: src/brpc/details/http_message.cpp [hunk 1]
```diff
@@ -630,7 +630,19 @@ void MakeRawHttpResponse(butil::IOBuf* response,
...
+        // A server MUST NOT send a Transfer-Encoding header field in any
+        // response with a status code of 1xx (Informational) or 204 (No
+        // Content).
+        h->RemoveHeader("Transfer-Encoding");
+        // https://www.rfc-editor.org/rfc/rfc7230#section-3.3.2
+        // A server MUST NOT send a Content-Length header field in any response
+        // with a status code of 1xx (Informational) or 204 (No Content).
+        h->RemoveHeader("Content-Length");
+    } else if (content) {
         h->RemoveHeader("Content-Length");
```
Comment (Huixxi) [inline src/brpc/details/http_message.cpp:646]: no_content是个bool类型，表示着一些状态码的status（包括no_content状态码和一些信息性状态码），而content则是butil::IOBuf*的指针类型，但两个变量的命名上看起来比较容易混淆，有没有更好的变量名来替换这个no_content

Comment (chenBright) [reply src/brpc/details/http_message.cpp:646]: 改成need_content如何？

Comment (Huixxi) [reply src/brpc/details/http_message.cpp:646]: is_invalid_content?

Comment (chenBright) [reply src/brpc/details/http_message.cpp:646]: 可以

Comment (chenBright) [reply src/brpc/details/http_message.cpp:646]: done
