### PR TITLE
bazel: fix with_bthread_tracer config setting

### LINKED ISSUE #3110: bazel: build failed with `--define with_bthread_tracer=true`
**Describe the bug**

```
In file included from <built-in>:402:
<command line>:3:9: error: macro name must be an identifier
#define -DBRPC_BTHREAD_TRACER 1
        ^
```

``` bash
src/bthread/task_tracer.cpp:26:10: error: 'absl/debugging/stacktrace.h' file not found with <angled> include; use "quotes" instead
#include <absl/debugging/stacktrace.h>
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
         "absl/debugging/stacktrace.h"
src/bthread/task_tracer.cpp:27:10: error: 'absl/debugging/symbolize.h' file not found with <angled> include; use "quotes" instead
#include <absl/debugging/symbolize.h>
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
         "absl/debugging/symbolize.h"
```

**To Reproduce**
```
$ bazel build --define with_bthread_tracer=true :brpc
```

**Expected behavior**

**Versions**
OS: ubuntu 20.04
Compiler: clang-12
brpc: master
protobuf: MODULE.bazel

**Additional context/screenshots**

### PR DESCRIPTION
**Pull request by icexin**
### What problem does this PR solve?

Issue Number: resolve #3110

Problem Summary:

### What is changed and the side effects?

Changed:

Side effects:
- Performance effects:

- Breaking backward compatibility: 

---
### Check List:
- Please make sure your changes are compilable.
- When providing us with a new feature, it is best to add related tests.
- Please follow [Contributor Covenant Code of Conduct](https://github.com/apache/brpc/blob/master/CODE_OF_CONDUCT.md).

### CODE REVIEW

File: src/bthread/task_tracer.cpp [hunk 1]
```diff
@@ -23,8 +23,8 @@
 #include "butil/fd_utility.h"
 #include "butil/memory/scope_guard.h"
 #include "butil/reloadable_flags.h"
-#include <absl/debugging/stacktrace.h>
-#include <absl/debugging/symbolize.h>
+#include "absl/debugging/stacktrace.h"
+#include "absl/debugging/symbolize.h"
```
Comment (chenBright) [inline src/bthread/task_tracer.cpp:27]: There is no need to modify this, use `<>` for third-party libraries.

File: BUILD.bazel [hunk 2]
```diff
@@ -405,7 +405,7 @@ cc_library(
     ]),
     defines = [] + select({
         "//bazel/config:brpc_with_bthread_tracer": [
-            "-DBRPC_BTHREAD_TRACER",
+            "BRPC_BTHREAD_TRACER",
```
Comment (chenBright) [inline BUILD.bazel:408]: Please use `BRPC_BTHREAD_TRACER=1`.

File: src/bthread/task_tracer.cpp (hunk 1 above)
Comment (icexin) [reply src/bthread/task_tracer.cpp:27]: 可以看一下 issue #3110 的编译错误信息，bazel对`<>`式的引用有报错
 
``` bash
src/bthread/task_tracer.cpp:26:10: error: 'absl/debugging/stacktrace.h' file not found with <angled> include; use "quotes" instead
#include <absl/debugging/stacktrace.h>
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
         "absl/debugging/stacktrace.h"
src/bthread/task_tracer.cpp:27:10: error: 'absl/debugging/symbolize.h' file not found with <angled> include; use "quotes" instead
#include <absl/debugging/symbolize.h>
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
         "absl/debugging/symbolize.h"
```

**Review by chenBright — APPROVED** [review]
LGTM
