### PR TITLE
Fix rdma complie error

### LINKED ISSUE #2706: RDMA build failure with 1.10
Compile failed with RDMA on.
`src/brpc/rdma/rdma_endpoint.cpp:1260:51: error: ‘class brpc::Socket’ has no member named ‘_bthread_tag’; did you mean ‘_read_buf’?`

This field was removed by commit [122355a29e2dd3341ad6f47e17682b482c45b7e4](https://github.com/apache/brpc/commit/122355a29e2dd3341ad6f47e17682b482c45b7e4).

### PR DESCRIPTION
**Pull request by chenBright**
### What problem does this PR solve?

Issue Number: resolve #2706

Problem Summary:

### What is changed and the side effects?

Changed:

修复#2560 导致rmda编译错误的问题。

Side effects:
- Performance effects(性能影响):

- Breaking backward compatibility(向后兼容性): 

---
### Check List:
- Please make sure your changes are compilable(请确保你的更改可以通过编译).
- When providing us with a new feature, it is best to add related tests(如果你向我们增加一个新的功能, 请添加相关测试).
- Please follow [Contributor Covenant Code of Conduct](../../master/CODE_OF_CONDUCT.md).(请遵循贡献者准则).

### CODE REVIEW

**Comment by chenBright** [comment]
@Tuvie @wwbmmm 看看这个PR

File: test/run_tests.sh [hunk 1]
```diff
@@ -22,7 +22,7 @@ rm core.*
 test_num=0
 failed_test=""
 rc=0
-test_bins="test_butil test_bvar bthread*unittest brpc*unittest"
+test_bins="brpc_rdma_unittest brpc_socket_unittest"
```
Comment (wwbmmm) [inline test/run_tests.sh:25]: 这个是不是测试忘记改回来了

Comment (chenBright) [reply test/run_tests.sh]: done
