### PR TITLE
Bugfix: bthread_worker_usage could exceed bthread_worker_count

### LINKED ISSUE #1231: bthread_worker_usage超出bthread_worker_count
**Describe the bug (描述bug)**
应用场景是dmkit当发起一个调用unit的请求时，bthread_worker_usage有时会超出bthread_worker_count很多，
当bthread_worker_count设置为9的时候，bthread_worker_usage最大会跳到100多，
当bthread_worker_count设置为48的时候，bthread_worker_usage最大会跳到1200多，
然后就会一直timeout，无论请求多少次。
此时如果过一会不管他，再次请求就好了。。。

**To Reproduce (复现方法)**
偶尔的访问调用会触发 bthread_worker_usage 的爆炸式增长，正常情况下是不会增长太多的，bthread_worker_usage也就长个1左右

**Expected behavior (期望行为)**
bthread_worker_usage波动正常，不会出现跳跃

**Versions (各种版本)**
OS: centos 7
Compiler: 
brpc: commit 2ae7f04c
protobuf: 2.5.0

**Additional context/screenshots (更多上下文/截图)**

WeChatbfc8219ad99a001851121a190aacd2ff

### LINKED ISSUE #2640: bthread_worker_usage这个统计值为何有时候会超时bthread
**Describe the bug (描述bug)**
在brpc的统计页面上，很容易就发现bthread_worker_usage的值
超过bthread_worker_count,理论上根据代码，bthread_worker_usage
的值不会超过TaskGroup的个数，因为代码
double TaskControl::get_cumulated_worker_time() {
    int64_t cputime_ns = 0;
    BAIDU_SCOPED_LOCK(_modify_group_mutex);
    const size_t ngroup = _ngroup.load(butil::memory_order_relaxed);
    for (size_t i = 0; i < ngroup; ++i) {
        if (_groups[i]) {
            cputime_ns += _groups[i]->_cumulated_cputime_ns;
        }
    }
    return cputime_ns / 1000000000.0;
}

这个函数是一秒钟统计一次，如果定时器完全准的话，一定不会超过ngroup的个数
因此这个值是否强依赖定时器，因而不一定完全准确，是否应该将
 cputime_ns / 1000000000.0;
更改为 cputime_ns / （real_elapse_time）;其中real_elapse_time是这个函数两次
调用的时间差。

**To Reproduce (复现方法)**

**Expected behavior (期望行为)**

**Versions (各种版本)**
OS:
Compiler:
brpc: 1.0.0
protobuf:

**Additional context/screenshots (更多上下文/截图)**
image

### LINKED ISSUE #2972: vars 监控中bthread_worker_usage > bthread_worker_count 是正常的么
如下图所示 bthread_worker_usage > bthread_worker_count , 正在使用的不应该<=上限么，这里是统计口径问题么？

Image

### PR DESCRIPTION
**Pull request by chenBright**
### What problem does this PR solve?

Issue Number: resolve #1231 , resolve #2640 , resolve #2972

Problem Summary:

### What is changed and the side effects?

Changed:

`bthread_worker_usage` should consist of `_cumulated_cputime_ns` and the CPU time of the task currently run by the worker.

Side effects:
- Performance effects:

- Breaking backward compatibility: 

---
### Check List:
- Please make sure your changes are compilable.
- When providing us with a new feature, it is best to add related tests.
- Please follow [Contributor Covenant Code of Conduct](https://github.com/apache/brpc/blob/master/CODE_OF_CONDUCT.md).

### CODE REVIEW

File: src/bthread/task_control.cpp [hunk 1]
```diff
@@ -524,12 +525,29 @@ void TaskControl::print_rq_sizes(std::ostream& os) {
...
+            // `_last_run_ns_in_tc' may have been updated multiple times,
+            // and `cputime_ns' will miss some cpu time, which is ok.
+            int64_t last_run_ns = g->_last_run_ns;
+            if (last_run_ns > _last_get_cumulated_time_ns) {
+                g->_last_run_ns_in_tc = last_run_ns;
+                cputime_ns += now - last_run_ns;
+            } else if (last_run_ns == g->_last_run_ns_in_tc) {
+                // The bthread is still running on the same worker.
+                cputime_ns += now - last_run_ns;
+            }
```
Comment (gitccl) [inline src/bthread/task_control.cpp]: This change may introduce a subtle race condition when sampling cumulative CPU time.
Suppose `bthread_worker_usage` starts sampling at T=0s, and a task also starts execution at the same time. The task keeps running continuously for 3s. According to the current implementation, `get_cumulated_worker_time()` will return approximately 0, 1, and 2 at T=0s, T=1s, and T=2s respectively — which is expected.

However, at T=3s, a race can occur as follows:
- The sampling thread first reads `_cumulated_cputime_ns`, which is still 0.
- Then, the worker thread updates `_last_run_ns` and `_cumulated_cputime_ns` to 3e9.
- The sampling thread then proceeds to read `_last_run_ns` = 3e9.
- Since `last_run_ns` > `_last_get_cumulated_time_ns`, it goes into the branch:
```
cputime_ns += now - last_run_ns;
```
But `now` was captured earlier and is slightly less than `last_run_ns`, resulting in a **negative delta**.
As a result, the sampling thread misses the 3 seconds of accumulated CPU time, causes `get_cumulated_worker_time()` at T=3s to return a smaller value than at T=2s(**maybe even return a negative value**), finally leads to a negative value in `bthread_worker_usage`.

To prevent this issue, `_cumulated_cputime_ns` and `_last_run_ns` should be read together under a consistent view. One possible approach without using a lock maybe to read `_last_run_ns` **before and after** reading `_cumulated_cputime_ns`, and verify that both `_last_run_ns` reads return the same value.

Comment (chenBright) [reply src/bthread/task_control.cpp]: The problem of negative delta ​​was previously considered, but was missed during implementation.

Comment (chenBright) [reply src/bthread/task_control.cpp]: > read `_last_run_ns` **before and after** reading `_cumulated_cputime_ns`, and verify that both `_last_run_ns` reads return the same value.

I guess your intention is to try to read `_cumulated_cputime_ns` again when the `_last_run_ns` read twice are different. However, this approach cannot guarantee that the value of `_cumulated_cputime_ns` read the second time is 3e9, and it may still read 0.

Comment (chenBright) [reply src/bthread/task_control.cpp]: https://rigtorp.se/isatomic/
> On the latest CPU microarchitectures (Skylake and Zen 2) AVX/AVX2 128b/256b aligned loads and stores are atomic even though Intel and AMD officially doesn’t guarantee this. 

Perhaps we can use the implicit feature of modern CPUs that 128-bit aligned load/store operations are atomic to implement atomic operations on combination of `_cumulated_cputime_ns` and `_last_run_ns`.

x86_64: `_mm_load_si128`, `_mm_store_si128`
Arm and later: `vld1q_s64`

For scenarios that do not support 128-bit atomic operations, use the lock to guarantee this. Only the worker thread and sample thread acquire the lock, and the sample thread acquires locks once a second. There is no lock contention between worker threads. So lock contention can be ignored.

Comment (gitccl) [reply src/bthread/task_control.cpp]: > > read `_last_run_ns` **before and after** reading `_cumulated_cputime_ns`, and verify that both `_last_run_ns` reads return the same value.
> 
> I guess your intention is to try to read `_cumulated_cputime_ns` again when the `_last_run_ns` read twice are different. However, this approach cannot guarantee that the value of `_cumulated_cputime_ns` read the second time is 3e9, and it may still read 0.

Yeah, you're right, it's still possible to read 0...

**Comment by chenBright** [comment]
@wwbmmm @yanglimingcn Please take a look.

**Comment by chenBright** [comment]
@wwbmmm @yanglimingcn Friendly ping!

File: src/bthread/task_control.cpp [hunk 2]
```diff
@@ -526,26 +533,51 @@ double TaskControl::get_cumulated_worker_time() {
...
     }
     return cputime_ns / 1000000000.0;
 }
 
+double TaskControl::get_cumulated_worker_time(TaskGroup* g) {
+    if (NULL == g) {
+        return 0.0;
+    }
+
+#if __x86_64__ || __ARM_NEON
```
Comment (wwbmmm) [inline src/bthread/task_control.cpp]: Maybe wrap these code in a data structure like 'AtomicInteger128' for better maintainability

File: src/bthread/task_group.h [hunk 3]
```diff
@@ -203,6 +206,14 @@ class TaskGroup {
 private:
 friend class TaskControl;
 
+    struct CPUTimeStat {
+        // Last scheduling time.
+        // If this value is negative,
+        // it means that it is the main task.
+        int64_t last_run_ns;
```
Comment (wwbmmm) [inline src/bthread/task_group.h]: This name is confusing. Maybe change to 'last_run_ns_and_state', and offer reader and writer function like 

```cpp
last_run_ns()
is_main_task()
set_last_run_ns(last_run_ns, is_main_task)
```

File: src/bthread/task_group.cpp [hunk 4]
```diff
@@ -292,7 +282,7 @@ int TaskGroup::init(size_t runqueue_capacity) {
     _cur_meta = m;
     _main_tid = m->tid;
     _main_stack = stk;
-    _last_run_ns = butil::cpuwide_time_ns();
+    _cpu_time_stat.last_run_ns = -m->cpuwide_start_ns;
```
Comment (yanglimingcn) [inline src/bthread/task_group.cpp]: why this is -m->cpuwide_start_ns ?

File: src/bthread/task_control.cpp (hunk 2 above)
Comment (chenBright) [reply src/bthread/task_control.cpp]: done

File: src/bthread/task_group.cpp (hunk 4 above)
Comment (chenBright) [reply src/bthread/task_group.cpp]: The higher bit for task type, main task is 1, otherwise 0. Worker usage does not calculate CPU time of the main task.

File: src/bthread/task_group.h (hunk 3 above)
Comment (chenBright) [reply src/bthread/task_group.h]: done

**Comment by chenBright** [comment]
```c++
void* test(void*) {
    while (!brpc::IsAskedToQuit()) {
        sleep(2);
        bthread_yield();
    }
}

for (int i = 0; i < 3; ++i) {
    bthread_t tid;
    bthread_start_background(&tid, NULL, test, NULL);
}
```

image


Start 3 bthreads and loop sleep for 2s. The value of bthread_worker_usage is correct, and the extra 1 comes from the epoll bthread.

File: src/bthread/task_control.cpp [hunk 5]
```diff
@@ -33,6 +33,13 @@
 #include "bthread/timer_thread.h"         // global_timer_thread
 #include <gflags/gflags.h>
 #include "bthread/log.h"
+#ifdef __x86_64__
+#include <x86intrin.h>
+#endif // __x86_64__
+
+#ifdef __ARM_NEON
+#include <arm_neon.h>
+#endif // __ARM_NEON
```
Comment (wwbmmm) [inline src/bthread/task_control.cpp]: This code can be removed

Comment (chenBright) [reply src/bthread/task_control.cpp]: done

**Comment by wwbmmm** [comment]
LGTM
