### PR TITLE
Bugfix: SignalTrace mode has memory access problem

### LINKED ISSUE #3031: Signal Trace has memory access problem
**Describe the bug**
In `TaskTracer::SignalTrace`, we put a  `Result*` in `SignalSync`. But if `SignalTrace` timeout, `Result` will be delete. This may cause memory access problem in the `SignalHandler` thread. I think it will be good if we store pcs by `std::vector<void *>`

### PR DESCRIPTION
**Pull request by CodeZHXS**
### What problem does this PR solve?

Issue Number: Fix #3031

Problem Summary: SignalTrace mode has memory access problem

### What is changed and the side effects?

Changed: use `Result` instead of `Result *`

Side effects:
- Performance effects:

- Breaking backward compatibility: 

---
### Check List:
- Please make sure your changes are compilable.
- When providing us with a new feature, it is best to add related tests.
- Please follow [Contributor Covenant Code of Conduct](https://github.com/apache/brpc/blob/master/CODE_OF_CONDUCT.md).

### CODE REVIEW

File: src/bthread/task_tracer.cpp [hunk 1]
```diff
@@ -356,15 +356,18 @@ void TaskTracer::SignalHandler(int, siginfo_t* info, void* context) {
...
     }
-    Result* result = signal_sync->result;
+    void *pcs[Result::MAX_TRACE_NUM];
     // Skip the first frame, which is the signal handler itself.
-    result->frame_count = absl::DefaultStackUnwinder(&result->ips[0], NULL,
-                                                     arraysize(result->ips),
-                                                     1, context, NULL);
+    int depth = absl::DefaultStackUnwinder(pcs, NULL, arraysize(pcs), 1,
+                                           context, NULL);
+    signal_sync->pcs.reserve(depth);
```
Comment (chenBright) [inline src/bthread/task_tracer.cpp]: Allocating memory in a signal handler is dangerous. Maybe we should make the type of result in SignalSync Result instead of Result*, just like before.

Comment (CodeZHXS) [reply src/bthread/task_tracer.cpp]: > Allocating memory in a signal handler is dangerous. Maybe we should make the type of result in SignalSync Result instead of Result*, just like before.

fix

File: src/bthread/task_tracer.h [hunk 2]
```diff
@@ -87,12 +87,12 @@ class TaskTracer {
 
     // For signal trace.
     struct SignalSync : public butil::SharedObject {
-        explicit SignalSync(Result* result) : result(result) {}
+        explicit SignalSync() {}
```
Comment (chenBright) [inline src/bthread/task_tracer.h]: No need for SignalSync().

File: src/bthread/task_tracer.cpp [hunk 3]
```diff
@@ -356,15 +356,14 @@ void TaskTracer::SignalHandler(int, siginfo_t* info, void* context) {
...
         return;
     }
-    Result* result = signal_sync->result;
     // Skip the first frame, which is the signal handler itself.
-    result->frame_count = absl::DefaultStackUnwinder(&result->ips[0], NULL,
-                                                     arraysize(result->ips),
-                                                     1, context, NULL);
+    signal_sync->result.frame_count = absl::DefaultStackUnwinder(signal_sync->result.ips, NULL, 
+                                    arraysize(signal_sync->result.ips), 1,
+                                           context, NULL);
```
Comment (chenBright) [inline src/bthread/task_tracer.cpp]: Format please.

**Review by chenBright — APPROVED** [review]
LGTM
